# Generated by Django 5.2.13 on 2026-04-20 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(choices=[('child', 'Child'), ('teenager', 'Teenager'), ('adult', 'Adult'), ('senior', 'Senior')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_probability',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_probability',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'age_group'], name='idx_gender_age_group'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'country_id'], name='idx_gender_country'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id', 'age_group'], name='idx_country_age_group'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age', 'gender'], name='idx_age_gender'),
        ),
    ]
