# ISO 3166-1 alpha-2 → full country name
COUNTRY_NAMES: dict[str, str] = {
    "AO": "Angola",
    "AU": "Australia",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "BJ": "Benin",
    "BR": "Brazil",
    "BW": "Botswana",
    "CA": "Canada",
    "CD": "DR Congo",
    "CF": "Central African Republic",
    "CG": "Republic of the Congo",
    "CI": "Côte d'Ivoire",
    "CM": "Cameroon",
    "CN": "China",
    "CV": "Cape Verde",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DZ": "Algeria",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ET": "Ethiopia",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GH": "Ghana",
    "GM": "Gambia",
    "GN": "Guinea",
    "GQ": "Equatorial Guinea",
    "GW": "Guinea-Bissau",
    "IN": "India",
    "JP": "Japan",
    "KE": "Kenya",
    "KM": "Comoros",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LY": "Libya",
    "MA": "Morocco",
    "MG": "Madagascar",
    "ML": "Mali",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MW": "Malawi",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "RW": "Rwanda",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SL": "Sierra Leone",
    "SN": "Senegal",
    "SO": "Somalia",
    "SS": "South Sudan",
    "ST": "São Tomé and Príncipe",
    "SZ": "Eswatini",
    "TD": "Chad",
    "TG": "Togo",
    "TN": "Tunisia",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "US": "United States",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    # Common extras for NLP parsing coverage
    "MX": "Mexico",
    "AR": "Argentina",
    "RU": "Russia",
    "PH": "Philippines",
    "PK": "Pakistan",
    "TR": "Turkey",
    "IT": "Italy",
    "ES": "Spain",
    "NL": "Netherlands",
    "SE": "Sweden",
    "NO": "Norway",
    "NZ": "New Zealand",
    "SG": "Singapore",
    "KR": "South Korea",
    "ID": "Indonesia",
    "MY": "Malaysia",
    "TH": "Thailand",
    "VN": "Vietnam",
    "UA": "Ukraine",
    "PL": "Poland",
    "GR": "Greece",
    "PT": "Portugal",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "IL": "Israel",
    "SA": "Saudi Arabia",
    "AE": "United Arab Emirates",
    "IQ": "Iraq",
    "IR": "Iran",
    "AF": "Afghanistan",
    "NP": "Nepal",
    "BD": "Bangladesh",
    "LK": "Sri Lanka",
    "MM": "Myanmar",
    "KH": "Cambodia",
    "VE": "Venezuela",
    "CO": "Colombia",
    "PE": "Peru",
    "CL": "Chile",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "CU": "Cuba",
    "HT": "Haiti",
    "DO": "Dominican Republic",
    "JM": "Jamaica",
    "TT": "Trinidad and Tobago",
    "HN": "Honduras",
    "GT": "Guatemala",
    "SV": "El Salvador",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "CZ": "Czech Republic",
    "SK": "Slovakia",
    "HU": "Hungary",
    "RO": "Romania",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "RS": "Serbia",
    "BA": "Bosnia and Herzegovina",
    "AL": "Albania",
    "MK": "North Macedonia",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "AZ": "Azerbaijan",
    "GE": "Georgia",
    "AM": "Armenia",
    "BY": "Belarus",
    "MD": "Moldova",
    "LT": "Lithuania",
    "LV": "Latvia",
    "EE": "Estonia",
    "FI": "Finland",
    "DK": "Denmark",
    "IE": "Ireland",
}


# Normalised country name / alias → ISO code (for NLP parser)
# Keys are lowercase; values are 2-letter ISO codes.
COUNTRY_LOOKUP: dict[str, str] = {}

# Build primary lookup from COUNTRY_NAMES (reverse)
for _code, _name in COUNTRY_NAMES.items():
    COUNTRY_LOOKUP[_name.lower()] = _code

# Manual aliases and common variants
_ALIASES: dict[str, str] = {
    "nigeria": "NG",
    "nigerian": "NG",
    "ghana": "GH",
    "ghanaian": "GH",
    "kenya": "KE",
    "kenyan": "KE",
    "tanzania": "TZ",
    "tanzanian": "TZ",
    "uganda": "UG",
    "ugandan": "UG",
    "ethiopia": "ET",
    "ethiopian": "ET",
    "south africa": "ZA",
    "south african": "ZA",
    "angola": "AO",
    "angolan": "AO",
    "cameroon": "CM",
    "cameroonian": "CM",
    "senegal": "SN",
    "senegalese": "SN",
    "benin": "BJ",
    "beninese": "BJ",
    "ivory coast": "CI",
    "côte d'ivoire": "CI",
    "cote d'ivoire": "CI",
    "ivory": "CI",
    "mali": "ML",
    "malian": "ML",
    "egypt": "EG",
    "egyptian": "EG",
    "morocco": "MA",
    "moroccan": "MA",
    "algeria": "DZ",
    "algerian": "DZ",
    "tunisia": "TN",
    "tunisian": "TN",
    "ghana": "GH",
    "liberia": "LR",
    "liberian": "LR",
    "sierra leone": "SL",
    "zambia": "ZM",
    "zambian": "ZM",
    "zimbabwe": "ZW",
    "zimbabwean": "ZW",
    "mozambique": "MZ",
    "mozambican": "MZ",
    "madagascar": "MG",
    "malagasy": "MG",
    "rwanda": "RW",
    "rwandan": "RW",
    "burundi": "BI",
    "burundian": "BI",
    "sudan": "SD",
    "sudanese": "SD",
    "somalia": "SO",
    "somali": "SO",
    "dr congo": "CD",
    "drc": "CD",
    "democratic republic of congo": "CD",
    "democratic republic of the congo": "CD",
    "republic of the congo": "CG",
    "congo": "CG",
    "botswana": "BW",
    "namibia": "NA",
    "namibian": "NA",
    "burkina faso": "BF",
    "chad": "TD",
    "chadian": "TD",
    "gabon": "GA",
    "gabonese": "GA",
    "togo": "TG",
    "togolese": "TG",
    "niger": "NE",
    "nigerien": "NE",
    "guinea": "GN",
    "guinean": "GN",
    "equatorial guinea": "GQ",
    "djibouti": "DJ",
    "eritrea": "ER",
    "eritrean": "ER",
    "malawi": "MW",
    "malawian": "MW",
    "lesotho": "LS",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "gambia": "GM",
    "gambian": "GM",
    "mauritania": "MR",
    "mauritanian": "MR",
    "mauritius": "MU",
    "cape verde": "CV",
    "cabo verde": "CV",
    "comoros": "KM",
    "seychelles": "SC",
    "south sudan": "SS",
    "western sahara": "EH",
    "central african republic": "CF",
    "united states": "US",
    "usa": "US",
    "america": "US",
    "united states of america": "US",
    "american": "US",
    "united kingdom": "GB",
    "uk": "GB",
    "britain": "GB",
    "great britain": "GB",
    "england": "GB",
    "british": "GB",
    "france": "FR",
    "french": "FR",
    "germany": "DE",
    "german": "DE",
    "brazil": "BR",
    "brazilian": "BR",
    "india": "IN",
    "indian": "IN",
    "china": "CN",
    "chinese": "CN",
    "japan": "JP",
    "japanese": "JP",
    "australia": "AU",
    "australian": "AU",
    "canada": "CA",
    "canadian": "CA",
    "mexico": "MX",
    "mexican": "MX",
    "south korea": "KR",
    "korea": "KR",
    "korean": "KR",
    "indonesia": "ID",
    "indonesian": "ID",
    "pakistan": "PK",
    "pakistani": "PK",
    "turkey": "TR",
    "turkish": "TR",
    "saudi arabia": "SA",
    "saudi": "SA",
    "netherlands": "NL",
    "dutch": "NL",
    "holland": "NL",
    "sweden": "SE",
    "swedish": "SE",
    "norway": "NO",
    "norwegian": "NO",
    "denmark": "DK",
    "danish": "DK",
    "finland": "FI",
    "finnish": "FI",
    "poland": "PL",
    "polish": "PL",
    "ukraine": "UA",
    "ukrainian": "UA",
    "russia": "RU",
    "russian": "RU",
    "spain": "ES",
    "spanish": "ES",
    "italy": "IT",
    "italian": "IT",
    "portugal": "PT",
    "portuguese": "PT",
    "singapore": "SG",
    "new zealand": "NZ",
    "greece": "GR",
    "greek": "GR",
    "israel": "IL",
    "israeli": "IL",
    "iran": "IR",
    "iranian": "IR",
    "iraq": "IQ",
    "iraqi": "IQ",
    "vietnam": "VN",
    "vietnamese": "VN",
    "thailand": "TH",
    "thai": "TH",
    "malaysia": "MY",
    "malaysian": "MY",
    "philippines": "PH",
    "filipino": "PH",
    "colombia": "CO",
    "colombian": "CO",
    "argentina": "AR",
    "argentinian": "AR",
    "venezuela": "VE",
    "venezuelan": "VE",
    "chile": "CL",
    "chilean": "CL",
    "peru": "PE",
    "peruvian": "PE",
}

COUNTRY_LOOKUP.update(_ALIASES)
